sql/musicbrainz_unaccent--1.0.0.sql /usr/share/postgresql/9.3/extension/
musicbrainz_unaccent.control /usr/share/postgresql/9.3/extension/
sql/musicbrainz_unaccent--unpackaged--1.0.0.sql /usr/share/postgresql/9.3/extension/
sql/uninstall_musicbrainz_unaccent.sql /usr/share/postgresql/9.3/extension/
README.musicbrainz_unaccent.md /usr/share/doc/postgresql-musicbrainz-unaccent/
musicbrainz_unaccent.so /usr/lib/postgresql/9.3/lib/
